#!/bin/bash

#SBATCH -N 1 # node count
#SBATCH --ntasks-per-node=10
#SBATCH --mem-per-cpu=4000
#SBATCH -t 3:00:00
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mjyuen@princeton.edu

# set the number of threads to be used for this run
export OMP_NUM_THREADS=10

cd /scratch/gpfs/mjyuen/

echo "run idba script"
echo ""
# run python script

idba_hybrid -r BE326_FW270712_BH2/BE326_FW270712_BH2_R.fasta -l BE326_FW270712_BH2/BE326_FW270712_BH2_U.fasta -o BE326_FW270712_BH2xHCD_7_hybrid --reference genome/HCD_7.fasta --num_threads 10


# idba_ud -r BE326_FW250111_BH2/BE326_FW250111_BH2xHCD_5_R.fasta -l BE326_FW250111_BH2/BE326_FW250111_BH2_U.fasta -o BE326_FW250111_BH2xHCD_5 --num_threads 12

echo ""
echo "idba done" 
