#!/bin/bash

#SBATCH -N 1 # node count
#SBATCH -c 10
#SBATCH -t 10:00:00
# sends mail when process begins and when it ends
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --mail-user=mjyuen@princeton.edu

# set the number of threads to be used for this run
export OMP_NUM_THREADS=10

cd /scratch/gpfs/mjyuen/DCO_TCO_NO14FW130912_R

# use already built index

# Mapping cRNA reads to cRNA contigs (def = very sensitive mode, -D 15 -R 2 -L 22 -i S,1,1.15; --un <path> to keep the unaligned reads)
/home/maglau/tools/bowtie2-2.2.5/bowtie2 --end-to-end --very-sensitive -p 10 --norc -t -x /scratch/gpfs/mjyuen/Sulfuritalea/Sulfuritalea -f -1 /scratch/gpfs/mjyuen/DCO_TCO_NO14FW130912_R/DCO_TCO_NO14FW130912_R1.fasta -2 /scratch/gpfs/mjyuen/DCO_TCO_NO14FW130912_R/DCO_TCO_NO14FW130912_R2.fasta -U /scratch/gpfs/mjyuen/DCO_TCO_NO14FW130912_R/DCO_TCO_NO14FW130912_U.fasta -S DCO_TCO_NO14FW130912_R.sam

